### ISSUE TITLE
Configuration conflicts？

### ISSUE THREAD

**Issue by ztz2** [danny8903/react-native-parallax-background#1]
Hello danny8903,  how to fix this?
Metro Bundler ready.
Loading dependency graph, done.
error: bundling failed: ambiguous resolution: module `D:\idea-workspace\react-native\ParallaxScrollViewBackground\index.js` tries to require `react-native`, but there are several files providing this module. You can delete or fix them:

  * `D:\idea-workspace\react-native\ParallaxScrollViewBackground\node_modules\react-native-parallax-background\node_modules\react-native\package.json`
  * `D:\idea-workspace\react-native\ParallaxScrollViewBackground\node_modules\react-native\package.json`

 BUNDLE  [android, dev] ./index.js ░░░░░░░░░░░░░░░░ 0.0% (0/1), failed.

**Comment by ztz2** [comment]
already solved， i just remove node_models then it is ok.

**Comment by danny8903** [comment]
thanks for the update. I will close this issue
